Libraries and Data

In [52]:
import medspacy
import pandas as pd
import re
from pathlib import Path
from medspacy.ner import TargetRule

ROOT = Path('../../data/raw')
data = ROOT / 'cases.csv'
metadata = ROOT / 'metadata.csv'

Visualizing

In [53]:
data = pd.read_csv(data)
metadata = pd.read_csv(metadata)

data.head()
metadata.head()

,article_id,authors,case_amount,doi,journal,journal_detail,keywords,license,link,major_mesh_terms,mesh_terms,pmcid,pmid,title,year
0,PMC5137649,"[C E Bailey, M B Fritz, L Webb, N B Merchant, ...",1,10.1308/003588414X13824511649977,Ann R Coll Surg Engl,2014 Jan;96(1):88E-90E.,NaN,CC BY,https://pubmed.ncbi.nlm.nih.gov/24417851/,"[Cysts / diagnosis, Stomach / abnormalities, S...","[Cysts / diagnosis, Stomach / abnormalities, S...",PMC5137649,24417851,Gastric duplication cyst masquerading as a muc...,2014
1,PMC9387390,"[Elias A Chamely, Bryan Hoang, Nadim S Jafri, ...",1,10.4293/CRSLS.2021.00094,CRSLS,2022 Feb 25;9(1):e2021.00094.,"[delayed gastric emptying, endoscopy, gastric ...",CC BY-NC-SA,https://pubmed.ncbi.nlm.nih.gov/36016812/,"[Adenocarcinoma / complications, Gastric Bypas...","[Adenocarcinoma / complications, Gastric Bypas...",PMC9387390,36016812,Palliative Endoscopic Salvage of a Functionall...,2022
2,PMC3437073,[M Y Al-Naami],1,NaN,J Family Community Med,1999 Jan;6(1):45-8.,"[abscess, spleen, tuberculous]",CC BY-NC-SA,https://pubmed.ncbi.nlm.nih.gov/23008596/,[],[Case Reports],PMC3437073,23008596,An unusual presentation of tuberculous splenic...,1999
3,PMC7102447,"[Zeid Nesheiwat, Pinang Shastri, Rohit Vyas, C...",1,10.1155/2020/7842591,Case Rep Cardiol,2020 Jan 11;2020:7842591.,NaN,CC BY,https://pubmed.ncbi.nlm.nih.gov/32257451/,[],[Case Reports],PMC7102447,32257451,A Case of Acute Massive Bioprosthetic Mitral V...,2020
4,PMC6354154,"[Patrícia Alves, Inês Sá, Miguel Brito, Cátia ...",1,10.1155/2019/2537480,Case Rep Obstet Gynecol,2019 Jan 16;2019:2537480.,NaN,CC BY,https://pubmed.ncbi.nlm.nih.gov/30792930/,[],[Case Reports],PMC6354154,30792930,An Early Diagnosis of an Ovarian Steroid Cell ...,2019

inner joining important mesh terms

In [54]:
full_data = pd.merge(data, metadata)
full_data = full_data[['case_text','gender', 'case_id', 'major_mesh_terms']]
full_data.head()

,case_text,gender,case_id,major_mesh_terms
0,A 44-year-old woman presented with a 3-day his...,Female,PMC5137649_01,"[Cysts / diagnosis, Stomach / abnormalities, S..."
1,A 57-year-old man with no significant past med...,Male,PMC9387390_01,"[Adenocarcinoma / complications, Gastric Bypas..."
2,A 55-year-old male presented with a gradually ...,Male,PMC3437073_01,[]
3,A 65-year-old male with a past medical history...,Male,PMC7102447_01,[]
4,A 30-year-old nulligravida presented herself i...,Female,PMC6354154_01,[]

picking the first case_text

In [55]:
text = full_data['case_text'][0]
print(text)

A 44-year-old woman presented with a 3-day history of right flank and lower quadrant abdominal pain associated with nausea and constipation. Her past medical, family and medication history were otherwise non-contributory and her physical examination was unremarkable. She underwent contrast enhanced computed tomography, demonstrating a 6cm cystic lesion between the stomach and body/tail of the pancreas (Fig 1). She subsequently underwent EUS-FNA, which revealed normal pancreatic echotexture and a cyst measuring 6cm x 9cm that was free of internal septations or associated masses (Fig 2) but compressed the stomach. FNA of the cyst demonstrated no evidence of malignancy but did show the presence of extracellular mucin as well as a carcinoembryonic antigen (CEA) level of 12,476.5ng/ml and a carbohydrate antigen (CA) 19-9 level of 6iu/ml, suggesting the diagnosis of a mucinous pancreatic cystic neoplasm. The patient was therefore referred for surgical resection.
A laparoscopic distal pancreatectomy was planned. At the time of the laparoscopic exploration, entrance to the lesser sac was first obtained and, on mobilising the posterior wall of the stomach, the lesion was noted to be tightly adherent to both the stomach and pancreas. The pancreas was mobilised free of the cyst and it was evident that the lesion originated from the stomach. Intraoperative endoscopy was performed and no mucosal abnormalities of the stomach were noted.
On further mobilisation, the cyst was adherent to the coeliac axis and the procedure was converted to an open resection. The stomach was fully mobilised and the gastric duplication cyst was noted to be arising from the posterior wall. It was dissected off the coeliac vessels and an enbloc resection of the cyst along with a portion of the posterior wall of the stomach with a surgical stapler was performed. Repeat oesophagogastroduodenoscopy revealed the presence of an intact staple line on the posterior stomach wall and no evidence of bleeding or leak. The gross margins were uninvolved.
Final pathology revealed a 9.5cm x 4.5cm x 2.0cm cyst with a smooth internal cyst wall consistent with a GDC (Figs 3-5). The patient was discharged home on postoperative day 4, doing well and tolerating a regular diet without any complications. On follow-up, she had complete resolution of her pain and nausea, and a return to regular bowel function and activity.

setting dictionary

In [56]:
dictionary = {
    # 1. Regiões Anatômicas e Estruturas Comuns
    "anatomy": [
        "heart",
        "lung",
        "lungs",
        "stomach",
        "liver",
        "kidney",
        "kidneys",
        "brain",
        "abdomen",
        "chest",
        "spine",
        "skin",
        "blood vessels",
        "artery",
        "vein",
        "bowel",
        "intestine",
        "colon",
        "pancreas",
        "esophagus",
        "pelvis",
        "neck",
        "head",
        "bone",
        "joint",
    ],
    # 2. Sintomas e Queixas Mais Recorrentes
    "symptom": [
        "pain",
        "chest pain",
        "abdominal pain",
        "headache",
        "fever",
        "cough",
        "shortness of breath",
        "dyspnea",
        "nausea",
        "vomiting",
        "fatigue",
        "dizziness",
        "diarrhea",
        "constipation",
        "edema",
        "swelling",
        "weight loss",
        "chills",
        "sweating",
        "palpitations",
        "weakness",
        "bleeding",
    ],
    # 3. Diagnósticos e Condições Crônicas/Agudas Frequentes
    "diagnosis": [
        "hypertension",
        "diabetes mellitus",
        "asthma",
        "pneumonia",
        "myocardial infarction",
        "stroke",
        "heart failure",
        "renal failure",
        "cirrhosis",
        "anemia",
        "sepsis",
        "cancer",
        "tumor",
        "infection",
        "embolism",
        "arrhythmia",
        "atrial fibrillation",
        "depression",
        "anxiety",
    ],
    # 4. Tratamentos e Procedimentos Padrão
    "treatment": [
        "surgery",
        "resection",
        "transplant",
        "chemotherapy",
        "radiation therapy",
        "dialysis",
        "intubation",
        "mechanical ventilation",
        "blood transfusion",
        "biopsy",
        "catheterization",
        "drainage",
        "physical therapy",
        "immunization",
    ],
    # 5. Medicamentos Mais Prescritos (Classes e Nomes Comuns)
    "medication": [
        "aspirin",
        "paracetamol",
        "ibuprofen",
        "insulin",
        "metformin",
        "omeprazole",
        "furosemide",
        "heparin",
        "warfarin",
        "atorvastatin",
        "enalapril",
        "amoxicillin",
        "morphine",
        "prednisone",
        "antibiotic",
        "analgesic",
    ],
    # 6. Exames Laboratoriais e de Imagem Padrão
    "exam": [
        "blood test",
        "complete blood count",
        "cbc",
        "electrocardiogram",
        "ecg",
        "ekg",
        "chest X-ray",
        "computed tomography",
        "ct scan",
        "magnetic resonance imaging",
        "mri",
        "ultrasound",
        "urinalysis",
        "echocardiogram",
        "biopsy report",
        "endoscopy",
    ],
}

In [57]:
nlp = medspacy.load()

# 2. Pega o componente TargetMatcher que já vem no pipeline
target_matcher = nlp.get_pipe('medspacy_target_matcher')

rules = []
for category, terms in dictionary.items():
  for term in terms:
    rules.append(TargetRule(literal=term, category=category.upper()))

target_matcher.add(rules)

processed_text = nlp(text)

for ent in processed_text.ents:
  print(f"Entidade: {ent.text} | Classe (Tipo para o Grafo): {ent.label_}")

2026-09-08 22:56:04.823 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 0 'A' marked as sentence start (span begin)
2026-09-08 22:56:04.824 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 28 'Her' marked as sentence start (span end next token)
2026-09-08 22:56:04.824 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 28 'Her' marked as sentence start (span begin)
2026-09-08 22:56:04.824 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 48 'She' marked as sentence start (span end next token)
2026-09-08 22:56:04.825 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 48 'She' marked as sentence start (span begin)
2026-09-08 22:56:04.825 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 76 'She' marked as sentence start (span end next token)
2026-09-08 22:56:04.826 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 76 'She' marked as sentence start (span begin)
2026-09-08 22:56:04.826 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 115 'FNA' marked as sentence start (span end next token)
2026-09-08 22:56:04.826 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 115 'FNA' marked as sentence start (span begin)
2026-09-08 22:56:04.827 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 174 'The' marked as sentence start (span end next token)
2026-09-08 22:56:04.827 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 174 'The' marked as sentence start (span begin)
2026-09-08 22:56:04.827 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 183 '
' marked as sentence start (span end whitespace)
2026-09-08 22:56:04.828 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] GAP DETECTED: tokens 183-183 (idx 971-971) between spans 970-974
2026-09-08 22:56:04.828 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 183 '
' marked as sentence start (whitespace in gap between spans)
2026-09-08 22:56:04.828 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 184 'A' marked as sentence start (span begin)
2026-09-08 22:56:04.828 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 191 'At' marked as sentence start (span end next token)
2026-09-08 22:56:04.829 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 191 'At' marked as sentence start (span begin)
2026-09-08 22:56:04.829 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 233 'The' marked as sentence start (span end next token)
2026-09-08 22:56:04.829 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 233 'The' marked as sentence start (span begin)
2026-09-08 22:56:04.829 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 253 'Intraoperative' marked as sentence start (span end next token)
2026-09-08 22:56:04.830 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 253 'Intraoperative' marked as sentence start (span begin)
2026-09-08 22:56:04.830 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 267 '
' marked as sentence start (span end whitespace)
2026-09-08 22:56:04.830 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] GAP DETECTED: tokens 267-267 (idx 1449-1449) between spans 1449-1450
2026-09-08 22:56:04.830 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 267 '
' marked as sentence start (whitespace in gap between spans)
2026-09-08 22:56:04.831 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 268 'On' marked as sentence start (span begin)
2026-09-08 22:56:04.831 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 290 'The' marked as sentence start (span end next token)
2026-09-08 22:56:04.831 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 290 'The' marked as sentence start (span begin)
2026-09-08 22:56:04.832 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 310 'It' marked as sentence start (span end next token)
2026-09-08 22:56:04.832 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 310 'It' marked as sentence start (span begin)
2026-09-08 22:56:04.832 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 342 'Repeat' marked as sentence start (span end next token)
2026-09-08 22:56:04.833 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 342 'Repeat' marked as sentence start (span begin)
2026-09-08 22:56:04.833 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 365 'The' marked as sentence start (span end next token)
2026-09-08 22:56:04.834 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 365 'The' marked as sentence start (span begin)
2026-09-08 22:56:04.834 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 371 '
' marked as sentence start (span end whitespace)
2026-09-08 22:56:04.834 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] GAP DETECTED: tokens 371-371 (idx 2042-2042) between spans 2042-2043
2026-09-08 22:56:04.835 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 371 '
' marked as sentence start (whitespace in gap between spans)
2026-09-08 22:56:04.835 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 372 'Final' marked as sentence start (span begin)
2026-09-08 22:56:04.836 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 402 'The' marked as sentence start (span end next token)
2026-09-08 22:56:04.836 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 402 'The' marked as sentence start (span begin)
2026-09-08 22:56:04.836 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 423 'On' marked as sentence start (span end next token)
2026-09-08 22:56:04.837 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 423 'On' marked as sentence start (span begin)
2026-09-08 22:56:04.837 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] Token/tag mapping: [(A, True), (44, False), (-, False), (year, False), (-, False), (old, False), (woman, False), (presented, False), (with, False), (a, False), (3, False), (-, False), (day, False), (history, False), (of, False), (right, False), (flank, False), (and, False), (lower, False), (quadrant, False), (abdominal, False), (pain, False), (associated, False), (with, False), (nausea, False), (and, False), (constipation, False), (., False), (Her, True), (past, False), (medical, False), (,, False), (family, False), (and, False), (medication, False), (history, False), (were, False), (otherwise, False), (non, False), (-, False), (contributory, False), (and, False), (her, False), (physical, False), (examination, False), (was, False), (unremarkable, False), (., False), (She, True), (underwent, False), (contrast, False), (enhanced, False), (computed, False), (tomography, False), (,, False), (demonstrating, False), (a, False), (6, False), (cm, False), (cystic, False), (lesion, False), (between, False), (the, False), (stomach, False), (and, False), (body, False), (/, False), (tail, False), (of, False), (the, False), (pancreas, False), ((, False), (Fig, False), (1, False), (), False), (., False), (She, True), (subsequently, False), (underwent, False), (EUS, False), (-, False), (FNA, False), (,, False), (which, False), (revealed, False), (normal, False), (pancreatic, False), (echotexture, False), (and, False), (a, False), (cyst, False), (measuring, False), (6, False), (cm, False), (x, False), (9, False), (cm, False), (that, False), (was, False), (free, False), (of, False), (internal, False), (septations, False), (or, False), (associated, False), (masses, False), ((, False), (Fig, False), (2, False), (), False), (but, False), (compressed, False), (the, False), (stomach, False), (., False), (FNA, True), (of, False), (the, False), (cyst, False), (demonstrated, False), (no, False), (evidence, False), (of, False), (malignancy, False), (but, False), (did, False), (show, False), (the, False), (presence, False), (of, False), (extracellular, False), (mucin, False), (as, False), (well, False), (as, False), (a, False), (carcinoembryonic, False), (antigen, False), ((, False), (CEA, False), (), False), (level, False), (of, False), (12, False), (,, False), (476.5ng, False), (/, False), (ml, False), (and, False), (a, False), (carbohydrate, False), (antigen, False), ((, False), (CA, False), (), False), (19, False), (-, False), (9, False), (level, False), (of, False), (6iu, False), (/, False), (ml, False), (,, False), (suggesting, False), (the, False), (diagnosis, False), (of, False), (a, False), (mucinous, False), (pancreatic, False), (cystic, False), (neoplasm, False), (., False), (The, True), (patient, False), (was, False), (therefore, False), (referred, False), (for, False), (surgical, False), (resection, False), (., False), (
, True), (A, True), (laparoscopic, False), (distal, False), (pancreatectomy, False), (was, False), (planned, False), (., False), (At, True), (the, False), (time, False), (of, False), (the, False), (laparoscopic, False), (exploration, False), (,, False), (entrance, False), (to, False), (the, False), (lesser, False), (sac, False), (was, False), (first, False), (obtained, False), (and, False), (,, False), (on, False), (mobilising, False), (the, False), (posterior, False), (wall, False), (of, False), (the, False), (stomach, False), (,, False), (the, False), (lesion, False), (was, False), (noted, False), (to, False), (be, False), (tightly, False), (adherent, False), (to, False), (both, False), (the, False), (stomach, False), (and, False), (pancreas, False), (., False), (The, True), (pancreas, False), (was, False), (mobilised, False), (free, False), (of, False), (the, False), (cyst, False), (and, False), (it, False), (was, False), (evident, False), (that, False), (the, False), (lesion, False), (originated, False), (from, False), (the, False), (stomach, False), (., False), (Intraoperative, True), (endoscopy, False), (was, False), (performed, False), (and, False), (no, False), (mucosal, False), (abnormalities, False), (of, False), (the, False), (stomach, False), (were, False), (noted, False), (., False), (
, True), (On, True), (further, False), (mobilisation, False), (,, False), (the, False), (cyst, False), (was, False), (adherent, False), (to, False), (the, False), (coeliac, False), (axis, False), (and, False), (the, False), (procedure, False), (was, False), (converted, False), (to, False), (an, False), (open, False), (resection, False), (., False), (The, True), (stomach, False), (was, False), (fully, False), (mobilised, False), (and, False), (the, False), (gastric, False), (duplication, False), (cyst, False), (was, False), (noted, False), (to, False), (be, False), (arising, False), (from, False), (the, False), (posterior, False), (wall, False), (., False), (It, True), (was, False), (dissected, False), (off, False), (the, False), (coeliac, False), (vessels, False), (and, False), (an, False), (enbloc, False), (resection, False), (of, False), (the, False), (cyst, False), (along, False), (with, False), (a, False), (portion, False), (of, False), (the, False), (posterior, False), (wall, False), (of, False), (the, False), (stomach, False), (with, False), (a, False), (surgical, False), (stapler, False), (was, False), (performed, False), (., False), (Repeat, True), (oesophagogastroduodenoscopy, False), (revealed, False), (the, False), (presence, False), (of, False), (an, False), (intact, False), (staple, False), (line, False), (on, False), (the, False), (posterior, False), (stomach, False), (wall, False), (and, False), (no, False), (evidence, False), (of, False), (bleeding, False), (or, False), (leak, False), (., False), (The, True), (gross, False), (margins, False), (were, False), (uninvolved, False), (., False), (
, True), (Final, True), (pathology, False), (revealed, False), (a, False), (9.5, False), (cm, False), (x, False), (4.5, False), (cm, False), (x, False), (2.0, False), (cm, False), (cyst, False), (with, False), (a, False), (smooth, False), (internal, False), (cyst, False), (wall, False), (consistent, False), (with, False), (a, False), (GDC, False), ((, False), (Figs, False), (3, False), (-, False), (5, False), (), False), (., False), (The, True), (patient, False), (was, False), (discharged, False), (home, False), (on, False), (postoperative, False), (day, False), (4, False), (,, False), (doing, False), (well, False), (and, False), (tolerating, False), (a, False), (regular, False), (diet, False), (without, False), (any, False), (complications, False), (., False), (On, True), (follow, False), (-, False), (up, False), (,, False), (she, False), (had, False), (complete, False), (resolution, False), (of, False), (her, False), (pain, False), (and, False), (nausea, False), (,, False), (and, False), (a, False), (return, False), (to, False), (regular, False), (bowel, False), (function, False), (and, False), (activity, False), (., False)]

Entidade: abdominal pain | Classe (Tipo para o Grafo): SYMPTOM
Entidade: nausea | Classe (Tipo para o Grafo): SYMPTOM
Entidade: constipation | Classe (Tipo para o Grafo): SYMPTOM
Entidade: computed tomography | Classe (Tipo para o Grafo): EXAM
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: pancreas | Classe (Tipo para o Grafo): ANATOMY
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: resection | Classe (Tipo para o Grafo): TREATMENT
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: pancreas | Classe (Tipo para o Grafo): ANATOMY
Entidade: pancreas | Classe (Tipo para o Grafo): ANATOMY
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: endoscopy | Classe (Tipo para o Grafo): EXAM
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: resection | Classe (Tipo para o Grafo): TREATMENT
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: resection | Classe (Tipo para o Grafo): TREATMENT
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: stomach | Classe (Tipo para o Grafo): ANATOMY
Entidade: bleeding | Classe (Tipo para o Grafo): SYMPTOM
Entidade: pain | Classe (Tipo para o Grafo): SYMPTOM
Entidade: nausea | Classe (Tipo para o Grafo): SYMPTOM
Entidade: bowel | Classe (Tipo para o Grafo): ANATOMY

In [58]:
without_stopwords_text = [token for token in processed_text if not token.is_stop and not token.is_punct and not '\n' in token.text]