Libraries and Data

In [6]:
import spacy
import pandas as pd
import re
from pathlib import Path

ROOT = Path('../../data/raw')
data = ROOT / 'cases.csv'
metadata = ROOT / 'metadata.csv'

Visualizing

In [7]:
data = pd.read_csv(data)
metadata = pd.read_csv(metadata)

data.head()
metadata.head()

,article_id,authors,case_amount,doi,journal,journal_detail,keywords,license,link,major_mesh_terms,mesh_terms,pmcid,pmid,title,year
0,PMC5137649,"[C E Bailey, M B Fritz, L Webb, N B Merchant, ...",1,10.1308/003588414X13824511649977,Ann R Coll Surg Engl,2014 Jan;96(1):88E-90E.,NaN,CC BY,https://pubmed.ncbi.nlm.nih.gov/24417851/,"[Cysts / diagnosis, Stomach / abnormalities, S...","[Cysts / diagnosis, Stomach / abnormalities, S...",PMC5137649,24417851,Gastric duplication cyst masquerading as a muc...,2014
1,PMC9387390,"[Elias A Chamely, Bryan Hoang, Nadim S Jafri, ...",1,10.4293/CRSLS.2021.00094,CRSLS,2022 Feb 25;9(1):e2021.00094.,"[delayed gastric emptying, endoscopy, gastric ...",CC BY-NC-SA,https://pubmed.ncbi.nlm.nih.gov/36016812/,"[Adenocarcinoma / complications, Gastric Bypas...","[Adenocarcinoma / complications, Gastric Bypas...",PMC9387390,36016812,Palliative Endoscopic Salvage of a Functionall...,2022
2,PMC3437073,[M Y Al-Naami],1,NaN,J Family Community Med,1999 Jan;6(1):45-8.,"[abscess, spleen, tuberculous]",CC BY-NC-SA,https://pubmed.ncbi.nlm.nih.gov/23008596/,[],[Case Reports],PMC3437073,23008596,An unusual presentation of tuberculous splenic...,1999
3,PMC7102447,"[Zeid Nesheiwat, Pinang Shastri, Rohit Vyas, C...",1,10.1155/2020/7842591,Case Rep Cardiol,2020 Jan 11;2020:7842591.,NaN,CC BY,https://pubmed.ncbi.nlm.nih.gov/32257451/,[],[Case Reports],PMC7102447,32257451,A Case of Acute Massive Bioprosthetic Mitral V...,2020
4,PMC6354154,"[Patrícia Alves, Inês Sá, Miguel Brito, Cátia ...",1,10.1155/2019/2537480,Case Rep Obstet Gynecol,2019 Jan 16;2019:2537480.,NaN,CC BY,https://pubmed.ncbi.nlm.nih.gov/30792930/,[],[Case Reports],PMC6354154,30792930,An Early Diagnosis of an Ovarian Steroid Cell ...,2019

inner joining important mesh terms

In [3]:
full_data = pd.merge(data, metadata)
full_data = full_data[['case_text','gender', 'case_id', 'major_mesh_terms']]
full_data.head()

,case_text,gender,case_id,major_mesh_terms
0,A 44-year-old woman presented with a 3-day his...,Female,PMC5137649_01,"[Cysts / diagnosis, Stomach / abnormalities, S..."
1,A 57-year-old man with no significant past med...,Male,PMC9387390_01,"[Adenocarcinoma / complications, Gastric Bypas..."
2,A 55-year-old male presented with a gradually ...,Male,PMC3437073_01,[]
3,A 65-year-old male with a past medical history...,Male,PMC7102447_01,[]
4,A 30-year-old nulligravida presented herself i...,Female,PMC6354154_01,[]

picking the first case_text

In [9]:
text = full_data['case_text'][0]
print(text)

A 44-year-old woman presented with a 3-day history of right flank and lower quadrant abdominal pain associated with nausea and constipation. Her past medical, family and medication history were otherwise non-contributory and her physical examination was unremarkable. She underwent contrast enhanced computed tomography, demonstrating a 6cm cystic lesion between the stomach and body/tail of the pancreas (Fig 1). She subsequently underwent EUS-FNA, which revealed normal pancreatic echotexture and a cyst measuring 6cm x 9cm that was free of internal septations or associated masses (Fig 2) but compressed the stomach. FNA of the cyst demonstrated no evidence of malignancy but did show the presence of extracellular mucin as well as a carcinoembryonic antigen (CEA) level of 12,476.5ng/ml and a carbohydrate antigen (CA) 19-9 level of 6iu/ml, suggesting the diagnosis of a mucinous pancreatic cystic neoplasm. The patient was therefore referred for surgical resection.
A laparoscopic distal pancreatectomy was planned. At the time of the laparoscopic exploration, entrance to the lesser sac was first obtained and, on mobilising the posterior wall of the stomach, the lesion was noted to be tightly adherent to both the stomach and pancreas. The pancreas was mobilised free of the cyst and it was evident that the lesion originated from the stomach. Intraoperative endoscopy was performed and no mucosal abnormalities of the stomach were noted.
On further mobilisation, the cyst was adherent to the coeliac axis and the procedure was converted to an open resection. The stomach was fully mobilised and the gastric duplication cyst was noted to be arising from the posterior wall. It was dissected off the coeliac vessels and an enbloc resection of the cyst along with a portion of the posterior wall of the stomach with a surgical stapler was performed. Repeat oesophagogastroduodenoscopy revealed the presence of an intact staple line on the posterior stomach wall and no evidence of bleeding or leak. The gross margins were uninvolved.
Final pathology revealed a 9.5cm x 4.5cm x 2.0cm cyst with a smooth internal cyst wall consistent with a GDC (Figs 3-5). The patient was discharged home on postoperative day 4, doing well and tolerating a regular diet without any complications. On follow-up, she had complete resolution of her pain and nausea, and a return to regular bowel function and activity.

In [10]:
nlp = spacy.load('en_core_web_sm')
processed_text = nlp(text)

for token in processed_text:
    print(f'text: {token.text}, lema: {token.lemma}, POS: {token.pos_}, lower: {token.lower_}')

text: A, lema: 11901859001352538922, POS: DET, lower: a
text: 44, lema: 11925070631239237109, POS: NUM, lower: 44
text: -, lema: 9153284864653046197, POS: PUNCT, lower: -
text: year, lema: 14889849580704678361, POS: NOUN, lower: year
text: -, lema: 9153284864653046197, POS: PUNCT, lower: -
text: old, lema: 2483095116303079762, POS: ADJ, lower: old
text: woman, lema: 18308318389743014884, POS: NOUN, lower: woman
text: presented, lema: 138130184627603044, POS: VERB, lower: presented
text: with, lema: 12510949447758279278, POS: ADP, lower: with
text: a, lema: 11901859001352538922, POS: DET, lower: a
text: 3, lema: 602994839685422785, POS: NUM, lower: 3
text: -, lema: 9153284864653046197, POS: PUNCT, lower: -
text: day, lema: 1608482186128794349, POS: NOUN, lower: day
text: history, lema: 6249630248276940353, POS: NOUN, lower: history
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: right, lema: 5943797630011647483, POS: ADJ, lower: right
text: flank, lema: 12585505121764813916, POS: NOUN, lower: flank
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: lower, lema: 14075063713394987089, POS: ADJ, lower: lower
text: quadrant, lema: 7996042779309914898, POS: ADJ, lower: quadrant
text: abdominal, lema: 4825016277875502055, POS: ADJ, lower: abdominal
text: pain, lema: 8558038558878807367, POS: NOUN, lower: pain
text: associated, lema: 409779398605839817, POS: VERB, lower: associated
text: with, lema: 12510949447758279278, POS: ADP, lower: with
text: nausea, lema: 15418423311033015569, POS: NOUN, lower: nausea
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: constipation, lema: 4749196292543209442, POS: NOUN, lower: constipation
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: Her, lema: 4115755726172261197, POS: PRON, lower: her
text: past, lema: 14080206577736366893, POS: ADJ, lower: past
text: medical, lema: 10039723232229819975, POS: ADJ, lower: medical
text: ,, lema: 2593208677638477497, POS: PUNCT, lower: ,
text: family, lema: 18292453351080475948, POS: NOUN, lower: family
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: medication, lema: 13479940910518016904, POS: NOUN, lower: medication
text: history, lema: 6249630248276940353, POS: NOUN, lower: history
text: were, lema: 10382539506755952630, POS: AUX, lower: were
text: otherwise, lema: 14975270065335614357, POS: ADV, lower: otherwise
text: non, lema: 15888754967501154131, POS: ADJ, lower: non
text: -, lema: 9153284864653046197, POS: ADJ, lower: -
text: contributory, lema: 4929606313063494408, POS: ADJ, lower: contributory
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: her, lema: 4115755726172261197, POS: PRON, lower: her
text: physical, lema: 3449592307697518307, POS: ADJ, lower: physical
text: examination, lema: 17851461254782948290, POS: NOUN, lower: examination
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: unremarkable, lema: 9112917473150866415, POS: ADJ, lower: unremarkable
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: She, lema: 6740321247510922449, POS: PRON, lower: she
text: underwent, lema: 4925305958269828818, POS: VERB, lower: underwent
text: contrast, lema: 2575714578448830368, POS: NOUN, lower: contrast
text: enhanced, lema: 15315377042691320518, POS: VERB, lower: enhanced
text: computed, lema: 11730250116939760274, POS: ADJ, lower: computed
text: tomography, lema: 8107350510396425797, POS: NOUN, lower: tomography
text: ,, lema: 2593208677638477497, POS: PUNCT, lower: ,
text: demonstrating, lema: 5547305781669311980, POS: VERB, lower: demonstrating
text: a, lema: 11901859001352538922, POS: DET, lower: a
text: 6, lema: 10999827425508017904, POS: NUM, lower: 6
text: cm, lema: 11920786500560237949, POS: NOUN, lower: cm
text: cystic, lema: 10898643098464443753, POS: ADJ, lower: cystic
text: lesion, lema: 9356977261877079399, POS: NOUN, lower: lesion
text: between, lema: 7508752285157982505, POS: ADP, lower: between
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: stomach, lema: 10587587228259269356, POS: NOUN, lower: stomach
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: body, lema: 12275956947298454125, POS: NOUN, lower: body
text: /, lema: 2466615745961202537, POS: SYM, lower: /
text: tail, lema: 15845025850280018348, POS: NOUN, lower: tail
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: pancreas, lema: 12611327663053628753, POS: NOUN, lower: pancreas
text: (, lema: 12638816674900267446, POS: PUNCT, lower: (
text: Fig, lema: 12500358444130381197, POS: PROPN, lower: fig
text: 1, lema: 5533571732986600803, POS: NUM, lower: 1
text: ), lema: 3842344029291005339, POS: PUNCT, lower: )
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: She, lema: 6740321247510922449, POS: PRON, lower: she
text: subsequently, lema: 7906080442506457862, POS: ADV, lower: subsequently
text: underwent, lema: 4925305958269828818, POS: VERB, lower: underwent
text: EUS, lema: 6852505396857352601, POS: PROPN, lower: eus
text: -, lema: 9153284864653046197, POS: PUNCT, lower: -
text: FNA, lema: 13690170654438549055, POS: PROPN, lower: fna
text: ,, lema: 2593208677638477497, POS: PUNCT, lower: ,
text: which, lema: 7063653163634019529, POS: PRON, lower: which
text: revealed, lema: 1901500303645832245, POS: VERB, lower: revealed
text: normal, lema: 7742806984934557812, POS: ADJ, lower: normal
text: pancreatic, lema: 1994884540289368049, POS: ADJ, lower: pancreatic
text: echotexture, lema: 15060337245803805598, POS: NOUN, lower: echotexture
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: a, lema: 11901859001352538922, POS: DET, lower: a
text: cyst, lema: 16443278900309779525, POS: NOUN, lower: cyst
text: measuring, lema: 4134526893188418915, POS: VERB, lower: measuring
text: 6, lema: 10999827425508017904, POS: NUM, lower: 6
text: cm, lema: 11920786500560237949, POS: NOUN, lower: cm
text: x, lema: 11123243248953317070, POS: SYM, lower: x
text: 9, lema: 1819085394523955522, POS: NUM, lower: 9
text: cm, lema: 11920786500560237949, POS: NOUN, lower: cm
text: that, lema: 4380130941430378203, POS: PRON, lower: that
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: free, lema: 17712913731469760764, POS: ADJ, lower: free
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: internal, lema: 6956465441722722121, POS: ADJ, lower: internal
text: septations, lema: 7251633425732414838, POS: NOUN, lower: septations
text: or, lema: 3740602843040177340, POS: CCONJ, lower: or
text: associated, lema: 18191730948251606032, POS: ADJ, lower: associated
text: masses, lema: 12710986754084908702, POS: NOUN, lower: masses
text: (, lema: 12638816674900267446, POS: PUNCT, lower: (
text: Fig, lema: 12500358444130381197, POS: PROPN, lower: fig
text: 2, lema: 15180167692696242062, POS: NUM, lower: 2
text: ), lema: 3842344029291005339, POS: PUNCT, lower: )
text: but, lema: 14560795576765492085, POS: CCONJ, lower: but
text: compressed, lema: 1532974760131752759, POS: VERB, lower: compressed
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: stomach, lema: 10587587228259269356, POS: NOUN, lower: stomach
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: FNA, lema: 2233667332159849192, POS: NOUN, lower: fna
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: cyst, lema: 16443278900309779525, POS: NOUN, lower: cyst
text: demonstrated, lema: 5547305781669311980, POS: VERB, lower: demonstrated
text: no, lema: 13055779130471031426, POS: DET, lower: no
text: evidence, lema: 2990301383317354291, POS: NOUN, lower: evidence
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: malignancy, lema: 11903428498097303715, POS: NOUN, lower: malignancy
text: but, lema: 14560795576765492085, POS: CCONJ, lower: but
text: did, lema: 2158845516055552166, POS: AUX, lower: did
text: show, lema: 1916734850589852068, POS: VERB, lower: show
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: presence, lema: 9563802622544222404, POS: NOUN, lower: presence
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: extracellular, lema: 3827474934130994910, POS: ADJ, lower: extracellular
text: mucin, lema: 14443258939047349966, POS: NOUN, lower: mucin
text: as, lema: 7437575085468336610, POS: ADV, lower: as
text: well, lema: 4525988469032889948, POS: ADV, lower: well
text: as, lema: 7437575085468336610, POS: ADP, lower: as
text: a, lema: 11901859001352538922, POS: DET, lower: a
text: carcinoembryonic, lema: 9957603894099003334, POS: ADJ, lower: carcinoembryonic
text: antigen, lema: 13235962292453342767, POS: NOUN, lower: antigen
text: (, lema: 12638816674900267446, POS: PUNCT, lower: (
text: CEA, lema: 12528792172112917377, POS: PROPN, lower: cea
text: ), lema: 3842344029291005339, POS: PUNCT, lower: )
text: level, lema: 15060127769916968652, POS: NOUN, lower: level
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: 12,476.5ng, lema: 4050232992645391396, POS: NOUN, lower: 12,476.5ng
text: /, lema: 2466615745961202537, POS: SYM, lower: /
text: ml, lema: 12487273070727829054, POS: PROPN, lower: ml
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: a, lema: 11901859001352538922, POS: DET, lower: a
text: carbohydrate, lema: 10933492356059757979, POS: ADJ, lower: carbohydrate
text: antigen, lema: 13235962292453342767, POS: NOUN, lower: antigen
text: (, lema: 12638816674900267446, POS: PUNCT, lower: (
text: CA, lema: 8902657483871908647, POS: PROPN, lower: ca
text: ), lema: 3842344029291005339, POS: PUNCT, lower: )
text: 19, lema: 11332016963924304957, POS: NUM, lower: 19
text: -, lema: 9153284864653046197, POS: SYM, lower: -
text: 9, lema: 1819085394523955522, POS: NUM, lower: 9
text: level, lema: 15060127769916968652, POS: NOUN, lower: level
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: 6iu, lema: 4764253352844632718, POS: NOUN, lower: 6iu
text: /, lema: 2466615745961202537, POS: SYM, lower: /
text: ml, lema: 12487273070727829054, POS: PROPN, lower: ml
text: ,, lema: 2593208677638477497, POS: PUNCT, lower: ,
text: suggesting, lema: 18092478065528711851, POS: VERB, lower: suggesting
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: diagnosis, lema: 12883373482306788754, POS: NOUN, lower: diagnosis
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: a, lema: 11901859001352538922, POS: DET, lower: a
text: mucinous, lema: 8064335938912649145, POS: ADJ, lower: mucinous
text: pancreatic, lema: 1994884540289368049, POS: ADJ, lower: pancreatic
text: cystic, lema: 10898643098464443753, POS: ADJ, lower: cystic
text: neoplasm, lema: 11104595626593975601, POS: NOUN, lower: neoplasm
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: The, lema: 7425985699627899538, POS: DET, lower: the
text: patient, lema: 14577208587912523278, POS: NOUN, lower: patient
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: therefore, lema: 12493256107732116026, POS: ADV, lower: therefore
text: referred, lema: 1199249557754039115, POS: VERB, lower: referred
text: for, lema: 16037325823156266367, POS: ADP, lower: for
text: surgical, lema: 11107462790820866388, POS: ADJ, lower: surgical
text: resection, lema: 7651881226219823465, POS: NOUN, lower: resection
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text:
, lema: 9999201909145832882, POS: SPACE, lower:

text: A, lema: 11901859001352538922, POS: DET, lower: a
text: laparoscopic, lema: 1101369610273252944, POS: ADJ, lower: laparoscopic
text: distal, lema: 7847203298843337673, POS: ADJ, lower: distal
text: pancreatectomy, lema: 15637808470351644835, POS: NOUN, lower: pancreatectomy
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: planned, lema: 6610255016299222351, POS: VERB, lower: planned
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: At, lema: 11667289587015813222, POS: ADP, lower: at
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: time, lema: 8885804376230376864, POS: NOUN, lower: time
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: laparoscopic, lema: 1101369610273252944, POS: NOUN, lower: laparoscopic
text: exploration, lema: 17818107371744676623, POS: NOUN, lower: exploration
text: ,, lema: 2593208677638477497, POS: PUNCT, lower: ,
text: entrance, lema: 2031847489866405900, POS: NOUN, lower: entrance
text: to, lema: 3791531372978436496, POS: ADP, lower: to
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: lesser, lema: 589070940943333110, POS: ADJ, lower: lesser
text: sac, lema: 15877086750440860717, POS: NOUN, lower: sac
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: first, lema: 11860158879560853892, POS: ADV, lower: first
text: obtained, lema: 8991116519625795538, POS: VERB, lower: obtained
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: ,, lema: 2593208677638477497, POS: PUNCT, lower: ,
text: on, lema: 5640369432778651323, POS: ADP, lower: on
text: mobilising, lema: 5840126203328151559, POS: VERB, lower: mobilising
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: posterior, lema: 18362218215777395045, POS: ADJ, lower: posterior
text: wall, lema: 14432890480967458232, POS: NOUN, lower: wall
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: stomach, lema: 10587587228259269356, POS: NOUN, lower: stomach
text: ,, lema: 2593208677638477497, POS: PUNCT, lower: ,
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: lesion, lema: 9356977261877079399, POS: NOUN, lower: lesion
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: noted, lema: 5316588462688733335, POS: VERB, lower: noted
text: to, lema: 3791531372978436496, POS: PART, lower: to
text: be, lema: 10382539506755952630, POS: AUX, lower: be
text: tightly, lema: 16837131230501861531, POS: ADV, lower: tightly
text: adherent, lema: 18382172429101697048, POS: NOUN, lower: adherent
text: to, lema: 3791531372978436496, POS: ADP, lower: to
text: both, lema: 7111508780595485950, POS: DET, lower: both
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: stomach, lema: 10587587228259269356, POS: NOUN, lower: stomach
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: pancreas, lema: 12611327663053628753, POS: NOUN, lower: pancreas
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: The, lema: 7425985699627899538, POS: DET, lower: the
text: pancreas, lema: 12611327663053628753, POS: NOUN, lower: pancreas
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: mobilised, lema: 5840126203328151559, POS: VERB, lower: mobilised
text: free, lema: 17712913731469760764, POS: ADJ, lower: free
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: cyst, lema: 16443278900309779525, POS: NOUN, lower: cyst
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: it, lema: 10239237003504588839, POS: PRON, lower: it
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: evident, lema: 7159288592323424690, POS: ADJ, lower: evident
text: that, lema: 4380130941430378203, POS: SCONJ, lower: that
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: lesion, lema: 9356977261877079399, POS: NOUN, lower: lesion
text: originated, lema: 760113054471905021, POS: VERB, lower: originated
text: from, lema: 7831658034963690409, POS: ADP, lower: from
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: stomach, lema: 10587587228259269356, POS: NOUN, lower: stomach
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: Intraoperative, lema: 12804095048452913845, POS: ADJ, lower: intraoperative
text: endoscopy, lema: 15105156825448744036, POS: NOUN, lower: endoscopy
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: performed, lema: 2369620111149368749, POS: VERB, lower: performed
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: no, lema: 13055779130471031426, POS: DET, lower: no
text: mucosal, lema: 9097218171671628549, POS: NOUN, lower: mucosal
text: abnormalities, lema: 3607268047365842840, POS: NOUN, lower: abnormalities
text: of, lema: 886050111519832510, POS: ADP, lower: of
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: stomach, lema: 10587587228259269356, POS: NOUN, lower: stomach
text: were, lema: 10382539506755952630, POS: AUX, lower: were
text: noted, lema: 5316588462688733335, POS: VERB, lower: noted
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text:
, lema: 962983613142996970, POS: SPACE, lower:

text: On, lema: 5640369432778651323, POS: ADP, lower: on
text: further, lema: 11294364119633739116, POS: ADJ, lower: further
text: mobilisation, lema: 2472528026925764705, POS: NOUN, lower: mobilisation
text: ,, lema: 2593208677638477497, POS: PUNCT, lower: ,
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: cyst, lema: 16443278900309779525, POS: NOUN, lower: cyst
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: adherent, lema: 18382172429101697048, POS: NOUN, lower: adherent
text: to, lema: 3791531372978436496, POS: ADP, lower: to
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: coeliac, lema: 14073845350964966616, POS: NOUN, lower: coeliac
text: axis, lema: 12830373804542000340, POS: NOUN, lower: axis
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: procedure, lema: 11972287917759495769, POS: NOUN, lower: procedure
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: converted, lema: 3335942246579838762, POS: VERB, lower: converted
text: to, lema: 3791531372978436496, POS: ADP, lower: to
text: an, lema: 15099054000809333061, POS: DET, lower: an
text: open, lema: 8092125317261700160, POS: ADJ, lower: open
text: resection, lema: 7651881226219823465, POS: NOUN, lower: resection
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: The, lema: 7425985699627899538, POS: DET, lower: the
text: stomach, lema: 10587587228259269356, POS: NOUN, lower: stomach
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: fully, lema: 9946396181595941590, POS: ADV, lower: fully
text: mobilised, lema: 5840126203328151559, POS: VERB, lower: mobilised
text: and, lema: 2283656566040971221, POS: CCONJ, lower: and
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: gastric, lema: 3898179352146084370, POS: ADJ, lower: gastric
text: duplication, lema: 15765380800946400605, POS: NOUN, lower: duplication
text: cyst, lema: 16443278900309779525, POS: NOUN, lower: cyst
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: noted, lema: 5316588462688733335, POS: VERB, lower: noted
text: to, lema: 3791531372978436496, POS: PART, lower: to
text: be, lema: 10382539506755952630, POS: AUX, lower: be
text: arising, lema: 11947388988416013985, POS: VERB, lower: arising
text: from, lema: 7831658034963690409, POS: ADP, lower: from
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: posterior, lema: 18362218215777395045, POS: ADJ, lower: posterior
text: wall, lema: 14432890480967458232, POS: NOUN, lower: wall
text: ., lema: 12646065887601541794, POS: PUNCT, lower: .
text: It, lema: 10239237003504588839, POS: PRON, lower: it
text: was, lema: 10382539506755952630, POS: AUX, lower: was
text: dissected, lema: 2997505704968432368, POS: VERB, lower: dissected
text: off, lema: 7039397736629347729, POS: ADP, lower: off
text: the, lema: 7425985699627899538, POS: DET, lower: the
text: coeliac, lema: 14073845350964966616, POS: NOUN, lower: coeliac
text: vessels, lema: 2023660552448857806, POS: NOUN, lower: vessels